os:
  - linux
  - osx
language: java
matrix:
  include:
    - os: linux
      jdk:
        - openjdk8
        - openjdk11
    - os: osx
      jdk:
        - openjdk11
env:
  - GOPATH="/tmp" GAUGE_ROOT="/tmp/gauge" GAUGE_TELEMETRY_ENABLED=false
addons:
  apt:
    packages:
      - golang-go
before_install:
  - if [ $TRAVIS_OS_NAME == "osx"]; then
      brew install golang;
    fi
install:
  - go run make.go
script: 
  - go version
  - cd ..
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - GAUGE_PREFIX=/tmp ./install_latest_gauge_nightly.sh
  - gauge -v
  - gauge config gauge_repository_url https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/
  - export PATH=/tmp/bin:$PATH
  - cd $TRAVIS_BUILD_DIR
  - go run make.go --install
  - cd ..
  - cd gauge-tests
  - gauge install
  - gauge -v
  - ./gradlew clean javaFT